openapi: 3.0.0
info:
  title: Car Price Prediction API
  version: 1.0.0
  description: |
    This API helps predict fair market dealer prices of used and new cars in the US and Canada.
servers:
  - url: https://mc-api.marketcheck.com
paths:
  /v2/predict/car/price:
    get:
      summary: Predict fair market dealer prices for a car
      description: |
        Predicts prices based on condition, VIN or year/make/model/trim, mileage (if used), and optional parameters such as title history, colors, location, etc.
      parameters:
        - name: car_type
          in: query
          description: Car condition - used or new
          required: true
          schema:
            type: string
            enum: [used, new]
        - name: vin
          in: query
          description: Vehicle Identification Number (VIN) of the car
          required: false
          schema:
            type: string
        - name: year
          in: query
          description: Year of the car (if VIN not provided)
          required: false
          schema:
            type: integer
        - name: make
          in: query
          description: Make of the car (if VIN not provided)
          required: false
          schema:
            type: string
        - name: model
          in: query
          description: Model of the car (if VIN not provided)
          required: false
          schema:
            type: string
        - name: trim
          in: query
          description: Trim of the car (if VIN not provided)
          required: false
          schema:
            type: string
        - name: miles
          in: query
          description: Mileage on the car (required if used)
          required: false
          schema:
            type: integer
        - name: is_certified
          in: query
          description: Certified Pre-Owned status
          required: false
          schema:
            type: boolean
            default: false
        - name: carfax_1_owner
          in: query
          description: Carfax one-owner flag
          required: false
          schema:
            type: boolean
            default: false
        - name: carfax_clean_title
          in: query
          description: Car's title history
          required: false
          schema:
            type: boolean
            default: false
        - name: base_exterior_color
          in: query
          description: Car's base exterior color
          required: false
          schema:
            type: string
        - name: base_interior_color
          in: query
          description: Car's base interior color
          required: false
          schema:
            type: string
        - name: transmission
          in: query
          description: Transmission type
          required: false
          schema:
            type: string
        - name: drivetrain
          in: query
          description: Car's drivetrain
          required: false
          schema:
            type: string
        - name: engine_block
          in: query
          description: Engine block info
          required: false
          schema:
            type: string
        - name: engine_size
          in: query
          description: Engine size in liters
          required: false
          schema:
            type: number
            format: float
        - name: cylinders
          in: query
          description: Number of cylinders
          required: false
          schema:
            type: integer
        - name: doors
          in: query
          description: Number of doors
          required: false
          schema:
            type: integer
        - name: highway_mpg
          in: query
          description: Highway mileage
          required: false
          schema:
            type: integer
        - name: city_mpg
          in: query
          description: City mileage
          required: false
          schema:
            type: integer
        - name: zip
          in: query
          description: Selling location's Zip Code
          required: false
          schema:
            type: string
        - name: latitude
          in: query
          description: Selling location's latitude
          required: false
          schema:
            type: string
        - name: longitude
          in: query
          description: Selling location's longitude
          required: false
          schema:
            type: string
        - name: country
          in: query
          description: Country for price prediction, allowed values: "us" or "ca"
          required: false
          schema:
            type: string
            enum: [us, ca]
      responses:
        '200':
          description: Successful price prediction response
          content:
            application/json:
              schema:
                type: object
                properties:
                  trade_in_value:
                    type: number
                    description: Trade-in value of the vehicle
                  private_party_value:
                    type: number
                    description: Estimated private party sale value
                  dealer_retail_value:
                    type: number
                    description: Dealer retail price estimate
                  msrp:
                    type: number
                    description: Manufacturer’s suggested retail price
        '400':
          description: Bad Request - Invalid or missing parameters
        '401':
          description: Unauthorized - API key missing or invalid
